
-- Edit this all changing type of int in id's

CREATE TABLE TB_AERODROMO (
	ID INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
	SG_AERODROMO CHAR(4) UNIQUE NOT NULL,
	NM_AERODROMO VARCHAR(100) UNIQUE NOT NULL,
	NM_CIDADE VARCHAR(50) NULL,
	SG_UF CHAR(2) NULL ,
	NM_PAIS VARCHAR(50) NOT NULL,
	NM_CONTINENTE  ENUM(
		'AMERICA DO SUL',
		'OCEANIA',
		'AMERICA DO NORTE',
		'AMERICA CENTRAL',
		'AFRICA',
		'EUROPA',
		'ASIA'
	) NOT NULL,
	
	CONSTRAINT CHK_CAN_UF CHECK (
		(NM_PAIS <> 'Brasil' AND SG_UF IS NULL) OR 
		NM_PAIS = 'Brasil'
		)
);

CREATE TABLE TB_EMPRESA (
	ID INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
	SG_EMPRESA CHAR(3) NOT NULL,
	NM_EMRPESA VARCHAR(100) NOT NULL,
	DS_TIPO_EMPRESA ENUM(
	'brasileira',
	'estrangeira',
	'não informado'
	)
);

CREATE TABLE TB_JUSTIFICATIVA(
	ID INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
	SG_JUSTIFICATIVA CHAR(2) UNIQUE NOT NULL,
	DS_JUSTIFICATIVA VARCHAR(255) NOT NULL
);

CREATE TABLE TB_TIPO_LINHA(
	ID INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
	CD_TIPO_LINHA CHAR(1) UNIQUE NOT NULL,
	DS_SERVICO_TIPO_LINHA  ,
	DS_NATUREZA_TIPO_LINHA
);

